# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HeroisMarvel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HeroisMarvel
  pod 'Alamofire', '~> 5.5'
  pod 'Kingfisher', '~> 6.0'
  pod 'SwiftHash', git: 'https://github.com/onmyway133/SwiftHash'
end
